/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebsiteDesignRouteImport } from './routes/services.website-design'
import { Route as ServicesSupportRouteImport } from './routes/services.support'
import { Route as ServicesDigitalDesignsRouteImport } from './routes/services.digital-designs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteDesignRoute = ServicesWebsiteDesignRouteImport.update({
  id: '/services/website-design',
  path: '/services/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSupportRoute = ServicesSupportRouteImport.update({
  id: '/services/support',
  path: '/services/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDigitalDesignsRoute = ServicesDigitalDesignsRouteImport.update({
  id: '/services/digital-designs',
  path: '/services/digital-designs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/digital-designs': typeof ServicesDigitalDesignsRoute
  '/services/support': typeof ServicesSupportRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/digital-designs': typeof ServicesDigitalDesignsRoute
  '/services/support': typeof ServicesSupportRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/digital-designs': typeof ServicesDigitalDesignsRoute
  '/services/support': typeof ServicesSupportRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services/digital-designs'
    | '/services/support'
    | '/services/website-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services/digital-designs'
    | '/services/support'
    | '/services/website-design'
  id:
    | '__root__'
    | '/'
    | '/services/digital-designs'
    | '/services/support'
    | '/services/website-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesDigitalDesignsRoute: typeof ServicesDigitalDesignsRoute
  ServicesSupportRoute: typeof ServicesSupportRoute
  ServicesWebsiteDesignRoute: typeof ServicesWebsiteDesignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-design': {
      id: '/services/website-design'
      path: '/services/website-design'
      fullPath: '/services/website-design'
      preLoaderRoute: typeof ServicesWebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/support': {
      id: '/services/support'
      path: '/services/support'
      fullPath: '/services/support'
      preLoaderRoute: typeof ServicesSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/digital-designs': {
      id: '/services/digital-designs'
      path: '/services/digital-designs'
      fullPath: '/services/digital-designs'
      preLoaderRoute: typeof ServicesDigitalDesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesDigitalDesignsRoute: ServicesDigitalDesignsRoute,
  ServicesSupportRoute: ServicesSupportRoute,
  ServicesWebsiteDesignRoute: ServicesWebsiteDesignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
